name: Go

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go-version: [1.19.x]

    steps:
      - name: Set up ${{ matrix.go-version }}
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Test
        run: make test-coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3

      - name: Build
        run: make build